### ISSUE TITLE
Part 3 input format

### ISSUE THREAD

**Issue by zhuowei** [utek-2018/competition-package#2]
The competition package says the input format for Part 3 is

```
Input:
CRACK | <ciphertext> [| <key length> for 3B only]

Output:
<key> | <message>           For 3A and 3D
<key1> <key2> ... | <message>     For 3B, output the key separated by spaces
```

but input/3a.in doesn't have "CRACK | " at the start of lines. Is this wrong?

**Comment by c2huc2hu** [comment]
The error is in the competition package. I'll push a fix shortly
